[minikube/bootstrap.sh] Update bootstrap configuration
instrumentisto/toolchain pull request #7
Opened 2019-02-15 10:54 UTC by targs08

Update minikube/bootstrap.sh configuration

2019-02-19 10:45 UTC, targs08 commented
FCM 

```
[minikube/bootstrap.sh] Allow change minikube args via environment variables (#7)
```

2019-02-20 08:40 UTC, tyranron requested changes

2019-02-20 08:40 UTC, tyranron commented on minikube/bootstrap.sh
> +    installHyperkitDriver
@targs08 only if `MINIKUBE_VM_DRIVER=hyperkit`.

2019-02-20 08:43 UTC, tyranron commented on minikube/bootstrap.sh
> +MINIKUBE_K8S_VER=${MINIKUBE_K8S_VER:-v1.13.3}
@targs08 I think `MINIKUBE_K8S_VER=v${MINIKUBE_K8S_VER:-1.13.3}` is better here for avoiding forgetting `v`.

2019-02-21 08:48 UTC, tyranron approved these changes

2019-02-21 12:49 UTC, merged