Add context kubernetes context
instrumentisto/toolchain pull request #8
Opened 2019-02-18 11:40 UTC by targs08

Add kubernetes context variable

2019-02-18 12:15 UTC, targs08 commented
FCM 

```
Add K8S_CONTEXTS environment 

Additionally:
- support bash BusyBox utils
```

2019-02-18 18:02 UTC, tyranron requested changes
Anything other is OK

2019-02-18 18:02 UTC, tyranron commented on kubernetes/gitlab-auth.sh
@targs08 we should add validation here that number of items in `k8sNamespaces` equals to number of items in `k8sContexts`. Otherwise UB is possible.

2019-02-20 08:49 UTC, tyranron approved these changes
Fixed

2019-02-20 08:49 UTC, tyranron commented on kubernetes/gitlab-auth.sh
> +if [ "${#k8sNamespaces[@]}" -ne "${#k8sContexts[@]}" ]; then
@targs08 follow the style of scrip and use `[[ ]]` instead of `[ ]`.

2019-02-20 12:46 UTC, merged